### ISSUE TITLE
Addition to CurseForge mods.

### ISSUE THREAD

**Issue by chilletize** [ItsDeltin/keysim#2]
Hello! I hope you can see this issue, could you please add your mod to CurseForge or the approved mod list? I really need your mod to use with MineMenu in my modpack but CurseForge won't approve it as yours isn't on the list.
![image](https://github.com/user-attachments/assets/a2b1d7f1-1058-41bc-a2b1-0ee164bdb6c2)

**Comment by ItsDeltin** [comment]
I will look into listing it on CurseForge, but in the meantime (or if I forget):

Everyone is allowed to use keysim in their modpacks and it can be downloaded by CurseForge. A link to this comment should be proof enough.

I actually originally created this mod for MineMenu! I'm glad this random thing I made half a decade ago helps you.

**Comment by chilletize** [comment]
Thank you so much for the comment and also for making this mod, you're amazing!
